name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [6.0.x, 7.0.x, 8.0.x]
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore SimpleCalculator.sln

      - name: Build
        run: dotnet build --configuration Release SimpleCalculator.sln

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        dotnet-version: [6.0.x, 7.0.x, 8.0.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore SimpleCalculator.sln

      - name: Run tests
        run: dotnet test --configuration Release SimpleCalculator.sln