name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleCalculator.sln

      - name: Build
        run: dotnet build --configuration Release SimpleCalculator.sln

  test_debug:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleCalculator.sln

      - name: Run tests in Debug configuration
        run: dotnet test --configuration Debug SimpleCalculator.sln

  test_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleCalculator.sln

      - name: Run tests in Release configuration
        run: dotnet test --configuration Release SimpleCalculator.sln

  analyze_code:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleCalculator.sln

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Run SonarScanner analysis
        run: |
          dotnet sonarscanner begin /k:"your_project_key" /d:sonar.host.url="your_sonar_url" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build --configuration Release SimpleCalculator.sln
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"