name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleCalculator.sln

      - name: Build
        run: dotnet build --configuration Release SimpleCalculator.sln

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleCalculator.sln

      - name: Run tests
        run: dotnet test --configuration ${{ matrix.configuration }} SimpleCalculator.sln

  analyze:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Run static code analysis
        run: dotnet sonarscanner begin /k:"your_project_key" -d:sonar.host.url="https://sonarcloud.io" -d:sonar.login="$SONAR_TOKEN"
      - name: Build
        run: dotnet build
      - name: Run tests
        run: dotnet test
      - name: End analysis
        run: dotnet sonarscanner end -d:sonar.login="$SONAR_TOKEN"