name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleCalculator.sln

      - name: Build
        run: dotnet build --configuration Release SimpleCalculator.sln

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleCalculator.sln

      - name: Run tests in Debug configuration
        run: dotnet test --configuration Debug SimpleCalculator.sln

      - name: Run tests in Release configuration
        run: dotnet test --configuration Release SimpleCalculator.sln

  code_analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleCalculator.sln

      - name: Install dotnet format tool
        run: dotnet tool install -g dotnet-format

      - name: Run code analysis
        run: dotnet format SimpleCalculator.sln --check --verbosity diagnostic